name: Tests

on: [pull_request]

jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install nightly
      run: rustup toolchain install nightly
    - name: Install WASM toolchain
      run: rustup target add wasm32-unknown-unknown --toolchain nightly 
    - name: Build
      run: bash ./scripts/build.sh
    - name: Run tests
      run: bash ./scripts/test.sh

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
      - name: Install nightly
        run: rustup toolchain install nightly
      - name: Install nightly rustfmt
        run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Run rustfmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
